[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\v/home/tabun)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\n1\0\0\0*\0\0\f\xca\0\0\x2\xf4\0\0\n1\0\0\0*\0\0\f\xca\0\0\x2\xf4\0\0\0\x1\0\0\0\0\x5V\0\0\n1\0\0\0*\0\0\f\xca\0\0\x2\xf4)

[FullScreen]
pos=@Point(2203 704)
screen=@Rect(1920 0 1366 768)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(666 644)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[RecentsMRL]
list=file:///home/tabun/Videos/Golang/2%20golang-goroutines/TUTORIAL%20GOLANG%20GOROUTINES%20BAHASA%20INDONESIA%20%5BYcVCTXjV0uA%5D.webm
times=8617928
