[main]
term=xterm-256color
term=foot
font = FiraCode:size=10 
line-height = 14
pad=10x10
#dpi-aware = yes

[colors]
alpha=0.85
background=242424
foreground=ffffff
flash=7f7f00
flash-alpha=0.5

[tweak]
font-monospace-warn=no

[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
