preload = /home/tabun/Pictures/nature.jpg
preload = /home/tabun/Pictures/lone-tree-1920x1080.jpg

wallpaper =,/home/tabun/Pictures/lone-tree-1920x1080.jpg

wallpaper = eDP-1,/home/tabun/Pictures/nature.jpg

